@startuml
actor "Мастер" as Master
participant "Функция входа в систему" as Login
participant "Функция отображения ЛК мастера" as Dash
participant "Функция обновления статуса записи" as StatusView
participant "База данных" as DB

== Вход в систему ==
Master -> Login: Вводит логин/пароль
Login -> DB: Аутентификация пользователя
DB --> Login: Вовзрат объекта конкретного мастера
alt Профиль мастера существует
    Login --> Master: Перенаправление в личный кабинет
else Профиля не существует
    Login --> Master: Сообщение "Вы ввели неверные данные"
end

== Работа с записями ==
Master -> Dash: Открывает личный кабинет
Dash -> DB: Запрос предстоящих записей 
Dash -> DB: Запрос статистики 
DB --> Dash: Данные
Dash --> Master: Показывает список клиентов и статистику

== Изменение статуса ==
Master -> StatusView: Обновляет статус записи
StatusView -> DB: Проверка прав 
StatusView -> DB: Обновление статуса записи
DB --> StatusView: Успех
StatusView --> Master: Обновляет страницу с сообщением об успехе
@enduml