@startuml
actor "Клиент" as Client
participant "Браузер" as Browser
participant "Функция получения занятых слотов" as API
participant "Форма записи" as Form
participant "База данных" as DB

== Проверка доступного времени ==
Client -> Browser: Выбирает мастера и дату
Browser -> API: GET запрос
API -> DB: Поиск расписания и и отпусков мастера
DB --> API: Данные графика
API -> DB: Поиск занятых расписаний на дату
DB --> API: Список записей
API -> API: Вычисление свободных часов
API --> Browser: Слоты в формате JSON
Browser --> Client: Показывает доступные кнопки времени

== Отправка формы ==
Client -> Browser: Заполняет данные и жмет "Записаться"
Browser -> Form: Отправка данных из формаы
Form -> Form: Проверка возраста
Form -> Form: Проверка наличия согласия
Form -> DB: Проверка: не в отпуске ли мастер?
Form -> DB: Проверка: не занято ли время?

alt Валидация успешна
    Form -> DB: Создание клиента (по телефону)
    Form -> DB: Создание записи со статусом "Ожидание"
    DB --> Form: ID записи
    Form --> Browser: Перенаправление на страницу успеха
    Browser --> Client: Показ подтверждения
else Ошибка (занято/нет согласия)
    Form --> Browser: Показ ошибок
    Browser --> Client: Просьба изменить данные записи
end
@startuml