@startuml
actor "Клиент" as Client
participant "Функция получения информации о мастере" as Detail
participant "База данных" as DB

Client -> Detail: Запрос ID мастера
Detail -> DB: Получение основной информации о мастере
Detail -> DB: Получение информации портфолио мастера
Detail -> DB: Получение информации об услугах мастера
DB --> Detail: Возврат данных из запроса
Detail -> Detail: Подсчёт выполненных записей у мастера
Detail --> Client: Отображение страницы мастера
@enduml