# Generated by Django 5.2 on 2026-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='specialty',
            field=models.CharField(help_text='Например: традиция, реализм, киберсигилизм', max_length=200, verbose_name='Специализация'),
        ),
    ]
