# Generated by Django 5.2 on 2026-02-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_master_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.CharField(blank=True, help_text='Например: реализм, традиция, графика', max_length=100, null=True, verbose_name='Категория')),
                ('body_part', models.CharField(blank=True, help_text='Например: рука, нога, спина', max_length=100, null=True, verbose_name='Часть тела')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Работа мастера',
                'verbose_name_plural': 'Портфолио мастеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
