# Generated by Django 5.2 on 2026-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_masterwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='sketches/', verbose_name='Желаемый эскиз'),
        ),
    ]
