# Generated by Django 5.2 on 2026-02-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Работает в салоне'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало отпуска')),
                ('end_date', models.DateField(verbose_name='Конец отпуска')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='main.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
            },
        ),
    ]
