# Generated by Django 5.2 on 2026-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_master_is_active_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='parental_consent',
            field=models.FileField(blank=True, help_text='cкан или фото согласия (для клиентов до 18 лет)', null=True, upload_to='consents/', verbose_name='cогласие родителей'),
        ),
    ]
