# Generated by Django 5.2 on 2026-03-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comment',
        ),
    ]
