@startuml
start

:Вход в раздел "Мое портфолио";
:Нажать "Добавить работу";
:Ввод названия и описания;
:Выбор категории;
:Выбор части тела;
:Загрузка изображения;

repeat
  :Отправка формы;
  :Валидация данных;

  if (Все поля валидны?) then (да)
    break
  else (нет)
    :Подсветка ошибочных полей;
    :Исправление только проблемных полей;
  endif
repeat while (Есть ошибки?) is (да)

:Сохранение работы в БД;
:Привязка к текущему мастеру;
:Отображение в общем списке портфолио;

stop
@enduml