@startuml
start

:Авторизация;

if (Данные верны?) then (да)
else (нет)
  :Сообщение "Неверные данные";
  :Перенаправление на главную;
  stop
endif

:Личный кабинет;
:Просмотр предстоящих записей;
:Выбор записи;
:Анализ данных;

if (Готов принять?) then (да)
  :Статус "Подтвержден";
  :Отправка POST-запроса;
  :Обновление записи в БД;
  :Проведение сеанса;
  :Статус "Выполнен";
  :Отправка POST-запроса;
  :Обновление записи в БД;
else (нет)
  :Статус "Отменен";
  :Отправка POST-запроса;
  :Обновление записи в БД;
endif

stop
@enduml