@startuml
title Диаграмма деятельности: Управление ресурсами (Админ)

start
:Вход в /admin;
fork
    :Раздел "Мастера";
    :Создание профиля сотрудника;
    :Привязка к системному User;
fork again
    :Раздел "Расписания";
    :Выбор дня недели для мастера;
    :Установка интервала (start_time - end_time);
fork again
    :Раздел "Отпуска";
    :Установка дат начала и конца;
end merge

:Сохранение изменений в БД;
note right
    Эти данные мгновенно влияют
    на логику выдачи слотов 
    в форме записи клиента.
end note

stop
@enduml