@startuml
title Диаграмма деятельности: Добавление работы в портфолио

start
:Вход в раздел "Мое портфолио";
:Нажать "Добавить работу";

repeat
    :Ввод названия и описания;
    :Выбор категории (реализм, олдскул и т.д.);
    :Выбор части тела (рука, нога и т.д.);
    :Загрузка изображения (ImageField);
    
    if (Все обязательные поля заполнены?) then (да)
        :Валидация формы;
        :Сохранение MasterWork;
        :Привязка работы к текущему Мастеру;
        break
    else (нет)
        :Подсветка пустых полей;
    endif
backward:Исправить ошибки;
repeat while (Форма не валидна)

:Отображение новой работы в общем списке;
stop
@enduml