@startuml
title Диаграмма деятельности: Управление ресурсами (Админ)

start
:Вход в админ-панель;
fork
    :Раздел "Мастера";
    :Создание профиля мастера;
    :Привязка мастера к его пользователю;
fork again
    :Раздел "Расписания";
    :Выбор дня недели для мастера;
    :Установка интервала (время начала работы и конца работы);
fork again
    :Раздел "Отпуска";
    :Установка дат начала и конца;
end merge

:Сохранение изменений в БД;

stop
@enduml