@startuml
title Диаграмма деятельности: Управление ресурсами (Админ)

start
:Вход в админ-панель;
partition Раздел "Добавить мастера" {
    :Создание профиля мастера с логином и паролем для личного кабинета;
}
partition Раздел "Услуги" {
    :Добавление/изменение предоставляемых услуг в салоне;
    :Привязка к услуге выполняющих её мастеров;
}
partition Раздел "Расписания" {
    :Выбор дня недели для мастера;
    :Установка интервала (время начала работы и конца работы);
    :Добавление/изменение расписания;
}
partition Раздел "Отпуска" {
    :Выбор дня начала и дня конца отпуска для мастера;
    :Указание причины отпуска;
    :Добавление/изменение отпуска;
}
:Сохранение изменений в БД;

stop
@enduml